default_language_version:
    python: python3.7

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-ast
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ['--maxkb=1000']
  # black
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
        exclude: ^tests/|^docs/
        args:
          - "--line-length=88"
  # flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: flake8
        exclude: ^tests/|^docs/
        args:
          - "--max-line-length=88"
          - "--max-complexity=19"
          - "--select=B,C,E,F,W,T4,B9"
          - "--ignore=F403,E402,E722,E203,W503,C901,E501"
  # bandit security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        exclude: ^tests/|^docs/
